# -*- coding: utf-8 -*-
"""GS - SERS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ScK9AYISPYv7b451EfGOeo4UM-jdXJg
"""

!pip install meteostat pandas matplotlib --quiet

from datetime import datetime
import pandas as pd
import matplotlib.pyplot as plt
from meteostat import Point, Daily

location = Point(-30.0331, -51.2300)

start = datetime(2024, 1, 1)
end = datetime(2025, 12, 31)

data = Daily(location, start, end)
df = data.fetch()

print("Dados meteorológicos diários:")
print(df.head())

df['prcp'] = df['prcp'].fillna(0)

df_monthly = df.resample('M').mean()
df_monthly['total_prcp'] = df['prcp'].resample('M').sum()

print("\nMédias mensais e precipitação total:")
print(df_monthly[['tavg', 'total_prcp']])

plt.figure(figsize=(12,5))
plt.plot(df_monthly.index, df_monthly['tavg'], marker='o', label='Temp. Média (°C)')
plt.title('Temperatura Média Mensal - Porto Alegre')
plt.xlabel('Mês')
plt.ylabel('Temperatura (°C)')
plt.grid(True)
plt.legend()
plt.show()

plt.figure(figsize=(12,5))
plt.bar(df_monthly.index, df_monthly['total_prcp'], color='blue', alpha=0.6)
plt.title('Precipitação Total Mensal - Porto Alegre')
plt.xlabel('Mês')
plt.ylabel('Precipitação (mm)')
plt.grid(True)
plt.show()

def risco_enchente(chuva_mm):
    if chuva_mm < 100:
        return "Baixo"
    elif chuva_mm < 200:
        return "Médio"
    else:
        return "Alto"

df_monthly['risco_enchente'] = df_monthly['total_prcp'].apply(risco_enchente)

print("\nRisco de Enchente Mensal:")
print(df_monthly[['total_prcp', 'risco_enchente']])